### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by AscendFB**

### CODE REVIEW

**Comment by AscendFB** [comment]
Looks like I've decreased the coverage for -0.005%. I think that is caused by the new hotkey for which I have not found any test file anywhere. Looks like the other hotkeys are also not covered yet.
Did I miss it somewhere?

**Comment by RickCarlino** [comment]
@AscendFB I can take care of things from here, thanks for the help! The coverage drop probably relates to the fact that you wrapped [these lines](https://github.com/FarmBot/Farmbot-Web-App/pull/1401/files#diff-85c0dcc27d280d8ad1ad7d4f1e834b16R33-R36) in a function, but the test suite (maybe?) never calls them. I'm not 100% sure yet, but this has happened to me in the past. I can write tests for this, no worries!

If you have any other changes, please submit a new PR on a different branch. Also, sorry for the slow reply, it was a holiday here in the US.

**Comment by AscendFB** [comment]
Thanks @RickCarlino for helping out, I really appreciate your help.

**Comment by AscendFB** [comment]
fixes #1373 and fixes #1298

**Pull request merged**
