### PR TITLE
Mostly Panel updates and style changes

### PR DESCRIPTION
**Pull request by AscendFB**
Hello 😀

### CODE REVIEW

**Comment by AscendFB** [comment]
Forgot to update test scripts ... I'll open new PR when ready.

**Comment by RickCarlino** [comment]
@AscendFB Sounds good. If you need any help with testing or have questions about our CI system please let me know.

**Comment by AscendFB** [comment]
Well, I've been struggling with that as you can see. I still try to figure out the currently shown errors (at #1391) from CI because all tests in my local terminal ran fine without errors. Is there anything different being checked in CircleCI? Is there a way to trigger these tests again or is a new PR needed when fixes are committed?

**Comment by RickCarlino** [comment]
@AscendFB I will have time to up the coverage for you on Monday if you would like (we're happy to get your contributions and understand that testing can be tedious).

To answer your question though, here's how I usually do it:

First, I can check coverage by running:

```
sudo docker-compose run web rake coverage:run
```

which will generate output like this:

```
This build: 
Statements: 0.2791%
Branches:   0.2306%
Functions:  0.2959%
Lines:      0.2871%
Aggregate:  0.2708%

Using data from 4 recent coverage builds.

Coverage history (newest to oldest):
staging: 97.046%
staging: 96.982%
staging: 96.982%
staging: 96.979%

=====================================
COVERAGE RESULTS
This build:     0.27083794% 
staging  build: 97.04648248% 968ee6c0
=====================================
Difference:     -96.77564454%
Pass?           no
```

This is useful, but does not tell you _why_ coverage does not pass. To know which files are missing coverage, you can run:

```
sudo docker-compose run web npm run test-slow
```

As the name implies, this test run will be much slower than `npm run test`. The reason it is slower is because the test suite will run a "coverage report". The coverage report will look like this:

image

The report above is an HTML file located at `coverage_fe/index.html`. It is dynamically generated after each run of `test-slow`. You can open it in any web browser via the `file:///` protocol.

You can click around and look for files that you have either authored or modified. In order for CI to pass, you must cause test coverage to _increase for all files created and modified_. Open the files that were modified and look for red text, which indicates that the line is untested code. Our test coverage is very high and most of the untested lines are legacy code that existed before the test suite was created:
image

In the example above, line 76 lacks test coverage. Please be sure when you do add assertions to the test suite, they are "realistic" and cover common use cases, plus edge cases. A unit test that simply executes a function without doing proper assertions is problematic because it makes test coverage look higher than it really is without actually being able to detect problems later.

I hope that helps answer your question! As mentioned, I'd be happy to write the unit tests for you as an example if you are unfamiliar with Jest, Enzyme or unit testing. Please let me know.

**Comment by gabrielburnworth** [comment]
To add to that, the full list of checks can be viewed [here](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/.circleci/config.yml).

The failing command checks that the code test coverage doesn't decrease more than a set threshold. Since the coverage decreased in the current PR because code that is no longer necessary was removed, in my opinion the PR #1391 is ready to merge as is.

As for your second question, CircleCI will automatically run again when changes are committed while a PR is open, so no new PR is needed.

Thanks again for the PR!

**Comment by AscendFB** [comment]
Thank you both for taking the time to make the testing procedure clear for me. That detailed writeup really helps me a lot and I really appreciate that! Hopefully your efforts will pay off with my contributions in the future 👍 

In the past I've only ran `npm run test` which didn't show any errors, now that I'm aware that coverage is also important I will rather run the `test-slow`. I just tried `run web rake coverage:run` and ` npm run test-slow` and it was working as expected.
In my recent changes I had no struggles with unit tests as they were pretty standard. But I'll be cautious if something comes up that I'm not yet familiar with and tell you to check what I've done. Its a whole new environment for me that I need to get familiar with so I start with pretty easy tasks.

I still got a few questions:
- Do I need to worry if one or more commits in the PR are marked with a red cross? 
image

- [In this test](https://circleci.com/gh/FarmBot/Farmbot-Web-App/944?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) it looks like something went wrong on CI side. Is it necessary to react in some way to repeat the test cycle like a retrigger?

- What can I do when CI failed because of a decreasing coverage (like #1391)? Write a comment in the PR to let you know what is missing?

**Comment by RickCarlino** [comment]
@AscendFB 

 > Do I need to worry if one or more commits in the PR are marked with a red cross?

This means that when you pushed that commit up, it did not pass CI. As long as the most recent commit passes CI, it's OK.

 > repeat the test cycle like a retrigger?

This is a known bug that we have unfortunately not had time to investigate. It is a bug in the CI configuration and _not_ a bug in your code. I do not know if non-admins have permission to restart failed builds, but there is a "rebuild" button.

image

Again, I don't know if you need admin rights to see the "rebuild" button, but you would get to the screen by clicking on the "details" view of Circle CI:

image

 > What can I do when CI failed because of a decreasing coverage (like #1391)? Write a comment in the PR to let you know what is missing?

If the use case is too difficult to test I will get a notification about it via Github. I am happy to write the tests if need be. I realize some use cases are not easy to test. In this case, I am back in the office after the weekend and can take a look today.

**Comment by AscendFB** [comment]
> Again, I don't know if you need admin rights to see the "rebuild" button, but you would get to the screen by clicking on the "details" view of Circle CI:

Yes, write permissions are needed, just FYI. But since that bug doesn't seem to occur often, this should not be a problem.

**Pull request closed without merging**
