### PR TITLE
trying to expand multilanguage support

### PR DESCRIPTION
**Pull request by DDDIM**
Hello!
This time "npm run typecheck" shows no errors.

On my local server I see translated all (almost) text, except help messages.

### CODE REVIEW

**Comment by RickCarlino** [comment]
@DDDIM This looks great. Thanks for the help.

I noticed in some places that you wrote:

```
t("Pin Guard ") + "3"
```

this is better written as:

```
t("Pin Guard {{ num }}", { num: 1 })
```

since some languages will place numbers infront of nouns rather than after them.

I can fix this and get it merged in my next pr :+1: .

**Comment by RickCarlino** [comment]
@DDDIM I have made some slight changes to this PR and will merge your work in here: https://github.com/FarmBot/Farmbot-Web-App/pull/684 Thanks.

**Comment by DDDIM** [comment]
Hello, Rick!

I have two questions about translations.

1. Is about file webpack/constants.ts.  How should I correctly add multilanguage support to it?
2. Is about how often do you upgrade https://my.farmbot.io with sources from github? 
It is interesting when will we see russian translation on central FarmBot Web-site.

**Comment by RickCarlino** [comment]
>  webpack/constants.ts. How should I correctly add multilanguage support to it

It is best to use `t()` inside of React components (files that end in `*.tsx`) rather than attempting to translate `constants.ts`. It is intentionally untranslated due to some intricacies with how i18next works and how the web app initializes.

 > how often do you upgrade https://my.farmbot.io with sources from github

We deploy when features are stable enough for an official release. Unfortunately, that means we don't really have a set schedule for updates. **I anticipate a new release in the next two weeks.** This is mostly a guess based on the current work tempo and can change without notice for a variety of reasons.

**Comment by DDDIM** [comment]
Hello! Thanks for support!
So if t() will compare large strings, it will be very slow process. Or not?
Maybe it will have sense working with enums and switch operator? 
Anyway, I am trying to follow your advice and here is contents of my ru.js file:

```
import { ToolTips } from "../../../webpack/constants";

module.exports = {
  ToolTips.MOVE:"РУССКИЙ ХЕЛП!",
    " regimen" : " режим",
    " sequence" : " функция", 
```
I thought that it will be a waste of letters to insert all content of ToolTips.MOVE const, so i replased it with ToolTips.MOVE, but it didn't work. What I did wrong?

**Comment by gabrielburnworth** [comment]
With #687 new `ToolTips` and `Content` phrases to translate will show up in `ru.js` after running `node public/app-resources/languages/_helper.js ru`.

**Comment by DDDIM** [comment]
Thanks for reply!
In file "constants.ts" I changed 54 line from:
`        helpText={ToolTips.MOVE}>`
to:
`        helpText={t(ToolTips.MOVE)}>`

then ran 
`node _helper.js ru`
from "languages" directory.
Nothing new added to "ru.js" file.
So I think this method do not work.
Please correct me if I am wrong.

**Pull request closed without merging**
