### PR TITLE
Remove Logs page tooltip

### PR DESCRIPTION
**Pull request by rampollaluis**
It's small but this is my first open source contribution ever. I'm not familiarized with Ruby so I tried to find the easiest issue and one that didn't need to use Ruby.

Just removed the tooltip like asked and the unnecessary import statements.

I really like what you guys are doing here, hopefully I can contribute more in the future.

### CODE REVIEW

**Comment by RickCarlino** [comment]
Thanks for contributing @rampollaluis ! I will take a deeper look on Monday.

**Comment by gabrielburnworth** [comment]
Thank you for your contribution!

As you may have noticed in the above checks status, the `tests failed on CircleCI`. 

There are two options for running and viewing test results:
* **CircleCI**
  * By clicking `Details` for the CircleCI check above (takes you to https://circleci.com/gh/FarmBot/Farmbot-Web-App/1940)
* **Locally**
  * For all tests, run `sudo docker-compose run web npm run test-very-slow`
  * For a single test file, run `sudo docker-compose run web npm run test frontend/logs/__tests__/index_test.tsx`

We use tests to help prevent regressions, but in this case we want to intentionally remove something from the web app, so the test will need to be updated too.

In much the same way as you removed the element and its related string import, you will need to remove the expected string and its import from the test:
https://github.com/FarmBot/Farmbot-Web-App/blob/51e06a0bb92827da1dce489c8bd035625f6faa92/frontend/logs/__tests__/index_test.tsx#L36

https://github.com/FarmBot/Farmbot-Web-App/blob/51e06a0bb92827da1dce489c8bd035625f6faa92/frontend/logs/__tests__/index_test.tsx#L6

**Comment by rampollaluis** [comment]
Ah yes, I feared the tests would fail for exactly that reason. I was also not sure if contributors were allowed to modify the tests as someone might try deleting a test case in order to get their tests to pass. Although I must admit, I tried searching for the test case and didn't find it. My mistake was using the search function for the whole repository instead of going to the frontend/logs/ folder. I guess I need to familiarize myself more with the project's structure before continuing to contribute.

Also, if I were to use CircleCI to run the tests, would I have to set it up in my forked repository so they run and I'm sure they pass before I create a pull request?

**Comment by gabrielburnworth** [comment]
Yes, you may set it up so that it runs for your fork. I run tests locally, but I believe @RickCarlino has done so and may be able to better answer your question about setting up CircleCI to run on a forked repository.

**Comment by rampollaluis** [comment]
Don’t worry, I’ll look into it and come back if I have any specific issue. Thank you guys!

**Comment by RickCarlino** [comment]
@rampollaluis You probably _can_ use CircleCI to run tests, but that is not an ideal long term solution. Here's a workflow that is more inline with how we do day-to-day development on the project:

**Install [Visual Studio Code](https://code.visualstudio.com/).** VSCode is the correct editor for this project. Even if you already have a preferred text editor, VSCode has better Typescript support than any editor. This project is written almost entirely in Typescript. Below are some VSCode shortcuts that will do a better job at searching the repo than Github's repo search can:

| Name | Hotkey | Description |
|------|--------|-------------|
| Find All References |`alt + shift + f12` | If you hover a variable and type this command, you will see a list of every file in the project that references the variable|
| Jump to Definition | `f12` | If you see a variable you do not understand, you can jump to its definition and see its source.|
| Global search | `ctrl + shift + f` | Searches the entire project for a search term.|
| Fuzzy finder | `ctrl + p` | Similar to the `t` hotkey in Github's web app.|

Additionally, VSCode will provide ["intellisense"](https://code.visualstudio.com/docs/languages/typescript#_intellisense) on variable names, suggest the most relevant method names, catch typos, etc.. Since VSCode and Typescript are both maintained by Microsoft, it has better language integration than any other editor.

**Install [Docker Compose](https://docs.docker.com/compose/install/) on your host machine and [run the server locally](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/ubuntu_example.sh).** Unit tests need to be run frequently during development and CircleCI will be very slow. It will take a similar level of effort to setup while not providing any benefits over a local setup. A better solution is to run the tests on your host machine. This will allow you to run a clone of the web app server on your desktop, allowing you to preview the changes.

The examples below assume you are running a Linux or Mac based machine.

Start a local server:
```
sudo docker-compose up
```

Run typechecks:
```
sudo docker-compose run web npm run typescript
```

Run tests:
```
sudo docker-compose run web npm run test
```

**Comment by rampollaluis** [comment]
@RickCarlino I have installed Docker Compose and ran examples to make sure it is working, and have carefully gone through the instructions to run locally. My only doubt is since I'll be running locally but I cant use `localhost`, `127.0.0.1` nor `0.0.0.0` in the `.env` file, should the `API_HOST` in this file be my public IP address? Thanks!

**Comment by RickCarlino** [comment]
@rampollaluis You can use the IP address on your LAN (usually something like `192.168.0.4`). You do not necessarily need to use a public facing IP address.

**Pull request merged**
