### PR TITLE
npm install step

### PR DESCRIPTION
**Pull request by yuvilio**
Needed to also ```npm install``` for the front end app relevant piece. Noting in the documentation.

Without it, i got this error after step 5:

```bash
ActionView::Template::Error (Unable to run node_modules/.bin/browserify. Ensure you have installed it with npm.
  (in /home/yuvilio/ws/apps/ruby/farmbot-web-app/app/assets/javascripts/application.js.jsx))
    10:     = stylesheet_link_tag "application"
    11:     = csrf_meta_tags
    12:     = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.min.js"
    13:     = javascript_include_tag "application"
    14:   %body{'ng-app' => 'FarmBot'}
    15:     .row
    16:       %nav.drop-shadow{ng_app: 'farmbot', ng_controller: 'nav'}  
```

### CODE REVIEW

**Comment by roryaronson** [comment]
Hey @yuvilio, thanks for getting involved! I don't write any of the software myself except for some occasional CSS stuff so I can't help too much. But I do know that the npm stuff was added just last week as our main developer @RickCarlino gets stuff setup for the farm designer.

**Comment by RickCarlino** [comment]
@yuvilio Welcome! Thanks for the help. So here's what's going on at the moment:

For the past 2 years, I've been the only dev on this particular project, which has gotten me into a bad habit of leaving master unstable. Here's what happened this week, and why things are in a somewhat half finished state:

 * Started adding React components to the Farm Designer, which was previously just a static HTML mockup.
 * hit some big issues with `rails-assets`, a bower component wrapper for Rails apps.
 * Discovered that ReduxJS does not officially support Bower, which we have used for js asset management up until this point.
 * decided to try NPM as an asset packager instead. 
 * Pulled the farm designer JS files out of the Rails asset pipeline and into a [possibly] temporary `/javascripts` folder that uses Gulp + NPM.

This week saw several sweeping changes (and admittedly, I didn't realize @roryaronson was going to send out the call for help email this weekend). As a result, things are in a somewhat half finished state over the weekend. Bear with me as I work towards a more stable master branch in the coming days and thanks again for the help!

**Comment by yuvilio** [comment]
No worries @RickCarlino.  I found you guys through google searches. I'm dipping in React/Redux as well. They sound like great choices for the interactive UI end.  Have you considered webpack as an approach? Not sure if that's too far an adjustment from your current setup.

**Comment by RickCarlino** [comment]
@yuvilio I've considered it. What kind of cool stuff can WebPack do vs. Browserify? I really hadn't put much thought into the module bundler for the app, to be honest. Prior to this, we were just using the asset pipeline (which is problematic now that everyone is using NPM instead of Bower.

If you think WebPack will be a win for the project and can maintain backwards compatibility with the codebase, sure, let's try it out.

**Pull request merged**
