### PR TITLE
Helptext and Tooltip updates

### PR DESCRIPTION
**Pull request by AscendFB**
Issue #1374 for reference.

Sorry for so many PRs from FarmBot repo to my fork. To keep track on my current coverage I update my fork often so I get reliable coverage values when running `coverage:run`.

### CODE REVIEW

**Comment by AscendFB** [comment]
What went wrong with CircleCI here? All checks passed but coverage report threw an error. 
Any ideas?

**Comment by RickCarlino** [comment]
@AscendFB Not sure I've seen that error before. I've re-started the build. Let's see if it was just a random fluke. :man_shrugging: If it continues to throw the exception, I can take a closer look on my local.

**Comment by gabrielburnworth** [comment]
It looks like the coveralls server is currently experiencing problems (`500 Build processing error`). The second graph on the status page (https://status.coveralls.io) shows similar behavior to when clients have received this error in the past.

**Comment by AscendFB** [comment]
@RickCarlino seems like the issue has been resolved (https://status.coveralls.io/). Can you trigger the tests again? If you run it on your PR I can close this one.

**Comment by RickCarlino** [comment]
@AscendFB Just merged. Thanks!

**Comment by roryaronson** [comment]
@AscendFB thank you **so** much for [all](https://github.com/FarmBot/Farmbot-Web-App/pulls?q=is%3Apr+is%3Aclosed+author%3AAscendFB) your contributions the last few months; it's been awesome to have more 3rd-party involvement! As we've mentioned before, we're hoping to get better and better at fostering the 3rd party developer community with the tools, info, and support needed to get involved.

We just wrote up a new documentation page for [3rd party developer prizes](https://developer.farm.bot/docs/3rd-party-developer-prizes), and we'd like award you with one to recognize your contributions to FarmBot and the community. DM me (rory@farmbot.io) to redeem :)

**Comment by AscendFB** [comment]
@roryaronson Thanks for those kind words Rory! I really enjoy doing this and love how the whole project evolved over the past few years. I am also really glad to work with such kind people, helping whenever they can. That really helps to stay motivated even when everything goes wrong at the thing you are working on. 

That documentation page about developer prizes looks really cool! I hope that will motivate some more people to start and share new projects or contribute  to the core features.

Huge ❤️  for all your work!!

**Pull request merged**
