### PR TITLE
Farm designer grid line improvements #1582

### PR DESCRIPTION
**Pull request by FabioDessi**

### CODE REVIEW

**Comment by RickCarlino** [comment]
@webnos Thanks for the PR- the current test failure is not related to your PR and I will fix it shortly. Sorry for the inconvenience- everything looks good and will be accepted once the issue is fixed.

**Comment by webnos** [comment]
Hi @RickCarlino thanks for the reply! I'll jump to some other other "good first issue".
If there something you want me to change on this one, Just let me know.
I'm glad to give my contribution on this project.

**Comment by roryaronson** [comment]
Thanks for the contribution @FabioDessi 🎉 

I think I miscommunicated a bit in the original issue. Rather than increasing the `stroke`'s darkness when zooming out, I think we should increase the `stroke-width`s. Here's what I think looks really nice on my screen, and offers the best distinction between the different grids at all zoom levels:

When zoomed in:
- minor `stroke-width="1"`, `stroke="rgba(0, 0, 0, 0.15)"`
- major `stroke-width="2"`, `stroke="rgba(0, 0, 0, 0.3)"`
- superior `stroke-width="4"`, `stroke="rgba(0, 0, 0, 0.4)"`

When zoomed out:
- minor is hidden
- major `stroke-width="3"`, `stroke="rgba(0, 0, 0, 0.3)"`
- superior `stroke-width="6"`, `stroke="rgba(0, 0, 0, 0.4)"`

Let me know what you think from a visual perspective!

**Comment by FabioDessi** [comment]
hi @roryaronson i think I took the directions too literally! 
Using stroke width indeed results in a better visual indication for the user!

@RickCarlino do i create a new branch from staging and create a new pull request to fix this?

I'll try to ask more for next issues before creating a new request!

**Comment by RickCarlino** [comment]
@FabioDessi Sorry for the slow reply, just getting back from the holidays and some travel. Yes, you should pull down the latest `staging` branch and start a new branch and pull request.

**Pull request merged**
