### PR TITLE
Complete Spanish translation file

### PR DESCRIPTION
**Pull request by dcriado**
Hello all,

This is my first public pull request, and my first PR in GitHub too, so I hope I am doing this properly.

I wanted to begin with contributing to something easier and more inocuous than writing pure code, that is:
- improving already-translated terms in `es.json`
- translating the rest of the terms in `es.json`

Let me know what I am supposed to do next. I hope I am contributing in a meaningful way, rather than annoying a group of busy people.

Cheers!

### CODE REVIEW

**Comment by dcriado** [comment]
@RickCarlino I have stumbled upon an issue while running `node _helper.js es`:

**Context** There are some keys that use the same characters in English and Spanish. For example:

```javascript
"translated": {
    "(x, y, z)": "(x, y, z)",
    "color": "color",
    "Sensor": "Sensor",
    "Slot": "Slot",
    "Z": "Z"
}
```

**Problem** When running `node _helper.js es`:
1. The script sees for 1=1 pairs need still a translation.
2. The script suppresses the 1=1 pairs under the `translated` key
3. The script adds these `key: value` pairs again under the `untranslated` key

**Expected behaviour**
1. The script sees 1=1 pairs under the `translated` key
2. It counts them as translated pairs

**Likely cause** The code block embraced by the conditional of **line 284**, in `_helper.js`:

```javascript
          if (key !== ordered[key]) {
            delete untranslated[key];
            translated[key] = ordered[key];
            if (debug) {
              translated[key] = replaceWithDebugString(key, debug, debugOption);
            }
          }
```

I have not created an issue because I suppose you are already aware of this problem. Let me know if there is anything else I am supposed to do.

**Comment by RickCarlino** [comment]
Thanks, @dcriado. I will merge this after CI passes. We appreciate your help!

**Comment by dcriado** [comment]
@RickCarlino You are welcome! Have a look at my last-minute comment, just in case it is of your interest.

**Comment by RickCarlino** [comment]
Thanks again @dcriado we have some updates planned for that file :tada:

**Comment by RickCarlino** [comment]
@dcriado We have updated the translation helper :+1:

**Comment by dcriado** [comment]
Awesome! Thank you for your feedback.

**Pull request merged**
