### PR TITLE
Hello! Trying to add some more language support.

### PR DESCRIPTION
**Pull request by DDDIM**
If I am doing something wrong, please tell me.
I am not familiar with node.js and web stuff, but familiar a little bit with javascript.
My purpose is to make full translation into Russian.
And also it will be good if this translation will be on main Web app server.
Thanks.

### CODE REVIEW

**Comment by RickCarlino** [comment]
@DDDIM That's great to hear! We're happy to help.

It looks like there are just a few minor issues with this pull request, but it looks very good overall.

One tip to check your work: You can run `npm run typecheck` to find syntax errors. There are currently two:

```
webpack/controls/move.tsx:53:15 - error TS1005: '{' expected.
53         title=t("Move")
                 ~

**Comment by RickCarlino** [comment]
@DDDIM That's great to hear! We're happy to help.

It looks like there are just a few minor issues with this pull request, but it looks very good overall.

One tip to check your work: You can run `npm run typecheck` to find syntax errors.

```
webpack/controls/move.tsx:53:15 - error TS1005: '{' expected.
53         title=t("Move")
                 ~
```

Should be changed to `title={t("Move")}` (with `{}` curly braces)

**Comment by RickCarlino** [comment]
@DDDIM I fixed the syntax issues and merged your additions in here: https://github.com/FarmBot/Farmbot-Web-App/pull/682

Thanks again.

**Comment by gabrielburnworth** [comment]
@DDDIM The translations you provided are now on [my.farm.bot](https://my.farm.bot/). Thanks!

**Pull request merged**
